/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAprenderRouteImport } from './routes/_authenticated/aprender'
import { Route as AuthenticatedDesempenhoRouteImport } from './routes/_authenticated/desempenho'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as ApiAiHealthRouteImport } from './routes/api/ai-health'
import { Route as AuthenticatedRedacaoIndexRouteImport } from './routes/_authenticated/redacao/index'
import { Route as AuthenticatedRedacaoTemaIaRouteImport } from './routes/_authenticated/redacao/tema-ia'
import { Route as AuthenticatedRedacaoTemaLivreRouteImport } from './routes/_authenticated/redacao/tema-livre'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAprenderRoute = AuthenticatedAprenderRouteImport.update({
  id: '/aprender',
  path: '/aprender',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesempenhoRoute = AuthenticatedDesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAiHealthRoute = ApiAiHealthRouteImport.update({
  id: '/api/ai-health',
  path: '/api/ai-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRedacaoIndexRoute =
  AuthenticatedRedacaoIndexRouteImport.update({
    id: '/redacao/',
    path: '/redacao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedacaoTemaIaRoute =
  AuthenticatedRedacaoTemaIaRouteImport.update({
    id: '/redacao/tema-ia',
    path: '/redacao/tema-ia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedacaoTemaLivreRoute =
  AuthenticatedRedacaoTemaLivreRouteImport.update({
    id: '/redacao/tema-livre',
    path: '/redacao/tema-livre',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aprender': typeof AuthenticatedAprenderRoute
  '/desempenho': typeof AuthenticatedDesempenhoRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/api/ai-health': typeof ApiAiHealthRoute
  '/redacao/tema-ia': typeof AuthenticatedRedacaoTemaIaRoute
  '/redacao/tema-livre': typeof AuthenticatedRedacaoTemaLivreRoute
  '/redacao/': typeof AuthenticatedRedacaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aprender': typeof AuthenticatedAprenderRoute
  '/desempenho': typeof AuthenticatedDesempenhoRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/api/ai-health': typeof ApiAiHealthRoute
  '/redacao/tema-ia': typeof AuthenticatedRedacaoTemaIaRoute
  '/redacao/tema-livre': typeof AuthenticatedRedacaoTemaLivreRoute
  '/redacao': typeof AuthenticatedRedacaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/aprender': typeof AuthenticatedAprenderRoute
  '/_authenticated/desempenho': typeof AuthenticatedDesempenhoRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/api/ai-health': typeof ApiAiHealthRoute
  '/_authenticated/redacao/tema-ia': typeof AuthenticatedRedacaoTemaIaRoute
  '/_authenticated/redacao/tema-livre': typeof AuthenticatedRedacaoTemaLivreRoute
  '/_authenticated/redacao/': typeof AuthenticatedRedacaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/aprender'
    | '/desempenho'
    | '/historico'
    | '/inicio'
    | '/api/ai-health'
    | '/redacao/tema-ia'
    | '/redacao/tema-livre'
    | '/redacao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/aprender'
    | '/desempenho'
    | '/historico'
    | '/inicio'
    | '/api/ai-health'
    | '/redacao/tema-ia'
    | '/redacao/tema-livre'
    | '/redacao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/aprender'
    | '/_authenticated/desempenho'
    | '/_authenticated/historico'
    | '/_authenticated/inicio'
    | '/api/ai-health'
    | '/_authenticated/redacao/tema-ia'
    | '/_authenticated/redacao/tema-livre'
    | '/_authenticated/redacao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAiHealthRoute: typeof ApiAiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aprender': {
      id: '/_authenticated/aprender'
      path: '/aprender'
      fullPath: '/aprender'
      preLoaderRoute: typeof AuthenticatedAprenderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desempenho': {
      id: '/_authenticated/desempenho'
      path: '/desempenho'
      fullPath: '/desempenho'
      preLoaderRoute: typeof AuthenticatedDesempenhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ai-health': {
      id: '/api/ai-health'
      path: '/api/ai-health'
      fullPath: '/api/ai-health'
      preLoaderRoute: typeof ApiAiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/redacao/': {
      id: '/_authenticated/redacao/'
      path: '/redacao'
      fullPath: '/redacao/'
      preLoaderRoute: typeof AuthenticatedRedacaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redacao/tema-ia': {
      id: '/_authenticated/redacao/tema-ia'
      path: '/redacao/tema-ia'
      fullPath: '/redacao/tema-ia'
      preLoaderRoute: typeof AuthenticatedRedacaoTemaIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redacao/tema-livre': {
      id: '/_authenticated/redacao/tema-livre'
      path: '/redacao/tema-livre'
      fullPath: '/redacao/tema-livre'
      preLoaderRoute: typeof AuthenticatedRedacaoTemaLivreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAprenderRoute: typeof AuthenticatedAprenderRoute
  AuthenticatedDesempenhoRoute: typeof AuthenticatedDesempenhoRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedRedacaoTemaIaRoute: typeof AuthenticatedRedacaoTemaIaRoute
  AuthenticatedRedacaoTemaLivreRoute: typeof AuthenticatedRedacaoTemaLivreRoute
  AuthenticatedRedacaoIndexRoute: typeof AuthenticatedRedacaoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAprenderRoute: AuthenticatedAprenderRoute,
  AuthenticatedDesempenhoRoute: AuthenticatedDesempenhoRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedRedacaoTemaIaRoute: AuthenticatedRedacaoTemaIaRoute,
  AuthenticatedRedacaoTemaLivreRoute: AuthenticatedRedacaoTemaLivreRoute,
  AuthenticatedRedacaoIndexRoute: AuthenticatedRedacaoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAiHealthRoute: ApiAiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
